# for now, use torch
from torch_imports import tensor, Tensor

def MAE() -> Tensor: ...
def MSE() -> Tensor: ...
def nll_loss() -> Tensor: ...
def CrossEntropy() -> Tensor: ...
def BinaryCrossEntropy() -> Tensor: ...